import Head from 'next/head'
import { FeaturedPosts } from '../sections/index'
import { PostCard, Categories, PostWidget } from '../components/blogpage'
import React from 'react'
import Layout from '../components/blogpage/Layout'
import { getPosts } from '../services'

export default function Home({ posts }) {
  return (
    <Layout>
      <div className="container mx-auto px-10 mb-8 text-white/90">
        <Head>
          <title>Blog Page</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <FeaturedPosts />

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-12">
          <div className="lg:col-span-8 col-span-1">
            {posts.map((post) => (
              <PostCard post={post.node} key={post.title} />
            ))}
          </div>
          <div className="lg:col-span-4 col-span-1">
            <div className="lg:sticky relative top-8">
              <PostWidget />
              <Categories />
            </div>
          </div>
        </div>
      </div>
    </Layout>
  )
}

export async function getStaticProps() {
  const posts = (await getPosts()) || []
  return {
    props: { posts },
  }
}
